# Generated by Django 3.0.6 on 2020-06-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuiNetPorttable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='PortID')),
                ('CurrentPort', models.CharField(max_length=5, verbose_name='本地端口')),
                ('RemotePort', models.CharField(max_length=5, verbose_name='远程端口')),
                ('NetworkProtocol', models.CharField(max_length=5, verbose_name='网络协议')),
                ('IsAlive', models.CharField(max_length=1, verbose_name='是否存活')),
                ('PortFlow', models.CharField(max_length=10, verbose_name='端口流量')),
                ('ProtStatus', models.CharField(max_length=10, verbose_name='端口状态')),
                ('RemoteIP', models.CharField(max_length=20, verbose_name='远程IP')),
                ('CurrentIP', models.CharField(max_length=20, verbose_name='本地IP')),
                ('UserID', models.CharField(max_length=20, verbose_name='用户ID')),
                ('PortEndTime', models.DateField(verbose_name='有效期')),
            ],
        ),
        migrations.CreateModel(
            name='RuiNetworkUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='UserID')),
                ('UserID', models.CharField(max_length=20, verbose_name='用户ID')),
                ('UserName', models.CharField(max_length=20, verbose_name='用户名称')),
                ('UserOnlineStatus', models.CharField(max_length=1, verbose_name='用户在线状态')),
                ('PortInfo', models.CharField(max_length=50, verbose_name='端口信息')),
                ('UserKey', models.CharField(max_length=20, verbose_name='用户密钥')),
                ('IsLimit', models.CharField(max_length=1, verbose_name='是否限制端口')),
                ('PortLimitNum', models.CharField(max_length=10, verbose_name='限制端口数目')),
                ('Email', models.CharField(max_length=20, verbose_name='Email')),
                ('UserDisable', models.CharField(max_length=1, verbose_name='用户是否禁用')),
            ],
        ),
    ]
